### ISSUE TITLE
Survival Guide dat swapped with Linkshell Concierge 

### ISSUE THREAD

**Issue by dannygils** [Ashenbubs/AshenbubsHD#2]
Issue: The Survival Guide dat appears to have been swapped with the Linkshell Concierge dat. Attached are two screenshots 

Testing: Ran FFXI (retail) with AshenbubsHD loaded with XIPivot and Windower4, examined the book near Ru'Lude Gardens Mog House (withAshenbubsHD.jpg). Ran FFXI (retail) with Windower4, did not load XIPivot or AshenbubsHD (withoutAshenbubsHD.jpg).

Does not appear to be isolated to just this Survival Guide.

I'm using your update from approx. 06:40 PM Thu Aug 27 2020

![withAshenbubsHD](https://user-images.githubusercontent.com/38189995/91586879-03332780-e924-11ea-8f61-09014d46d45e.jpg)
![withoutAshenbubsHD](https://user-images.githubusercontent.com/38189995/91586889-06c6ae80-e924-11ea-986d-e5718d9f7dc1.jpg)

**Comment by Ashenbubs** [comment]
Looks like some DAT files that contain client side data like NPC names were in a batch update a while ago - I must have missed these.  Thanks for bringing this to my attention.

I've now checked and removed any non-texture data DAT file from GitHub.

**Comment by dannygils** [comment]
You rock! Closing. :)
