### ISSUE TITLE
Missing gear texture

### ISSUE THREAD

**Issue by undeadkasper** [Ashenbubs/AshenbubsHD#8]
Sakpata's armor set missing upgraded texture.
![pol 2021-02-18 18-57-23](https://user-images.githubusercontent.com/6835542/108437461-68087400-721b-11eb-8d09-35bbbad539e1.png)
Perhaps not an issue, only posting because beta release said included all armors and weapons.
Thank you for all the hard work!

**Comment by Ashenbubs** [comment]
Aware of issue - Armor was only added last week - I put out a tweet yesterday saying this is currently being worked on along with all other new armor sets.  Hopefully resolve this shortly.

**Comment by Ashenbubs** [comment]
Armour has been completed, will be available shortly in new packs.

![8C8EC37F-EFB5-4706-9F8A-959990DD6A5C](https://user-images.githubusercontent.com/61240482/109328275-2eee8600-7851-11eb-9125-d4057eec9367.png)

New texture packs will appear on NexusMods soon - Please stay tuned here and on Twitter.

Twitter.com/AshenbubsHD
